#!/bin/sh

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

USERNAME='pixelated'
WORKDIR='/var/lib/pixelated'
ETCDIR='/etc/pixelated'

if ! id -u $USERNAME 2>/dev/null; then
  adduser --system $USERNAME --home $WORKDIR --disabled-password --shell /bin/sh --ingroup nogroup
fi

if [ ! -d $WORKDIR ]; then
  mkdir -p $WORKDIR
  chown $USERNAME:nogroup -R $WORKDIR

if [ ! -d $ETCDIR ]; then
  mkdir -p $ETCDIR
  chown $USERNAME:nogroup -R $ETCDIR
fi

systemctl restart pixelated-server
