#!/bin/sh

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

USERNAME='pixelated'
WORKDIR='/var/lib/pixelated'
ETCDIR='/etc/pixelated'

if ! ( /usr/bin/getent passwd $USERNAME > /dev/null ); then
  adduser --system $USERNAME --home $WORKDIR --disabled-password --shell /bin/sh --ingroup nogroup
fi

if [ ! -d $WORKDIR ]; then
  mkdir -p $WORKDIR
fi
chown $USERNAME:nogroup -R $WORKDIR

if [ ! -d $ETCDIR ]; then
  mkdir -p $ETCDIR
fi
chown $USERNAME:nogroup -R $ETCDIR

service pixelated-server restart
